### ISSUE TITLE
Beautify the UI using css

### ISSUE THREAD

**Issue by frextrite** [frextrite/PrimeCheckerJS#1]
Add a css file and beautify the layout.

**Comment by eb-h** [comment]
Hey, the javascript and css in the project seem to be missing from the repo 

https://github.com/frextrite/PrimeCheckerJS/blob/136101a441c09ff50c5c348a5f6a5c9e018fe549/index.html#L8 isn't there.

**Comment by frextrite** [comment]
Hey @eric-horvat, this project is still in early stages of development. I'll be adding files along the way. BTW this issue concerns with the addition of a css file too.
